default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
    - id: black
      args: [--check, --diff, --line-length=150]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8