name: MR validation

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check_mr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Code analysis
        run: |
          pre-commit run -a

      - name: Run tests
        run: |
          pytest . -n auto